// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	 "strings"

	"github.com/atom-apps/storage/modules/storages/controller"
	"github.com/atom-providers/jwt"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routeUploadController(engine fiber.Router, controller *controller.UploadController) {
	groupPrefix := "/"+strings.TrimLeft(engine.(*fiber.Group).Prefix,"/")
	engine.Post(strings.TrimPrefix("/v1/storages/uploads/dir/:id<int>", groupPrefix), DataFunc2(controller.Dir, JwtClaim[jwt.Claims](ClaimParamError), Integer[uint64]("id", PathParamError)))
	engine.Post(strings.TrimPrefix("/v1/storages/uploads/posts", groupPrefix), DataFunc1(controller.Posts, JwtClaim[jwt.Claims](ClaimParamError)))
}
