// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	 "strings"

	"github.com/atom-apps/storage/modules/storages/controller"
	"github.com/atom-apps/storage/modules/storages/dto"
	"github.com/atom-apps/storage/common"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routeDriverController(engine fiber.Router, controller *controller.DriverController) {
	groupPrefix := "/"+strings.TrimLeft(engine.(*fiber.Group).Prefix,"/")
	engine.Get(strings.TrimPrefix("/v1/storages/drivers/:id<int>", groupPrefix), DataFunc1(controller.Show, Integer[uint64]("id", PathParamError)))
	engine.Get(strings.TrimPrefix("/v1/storages/drivers", groupPrefix), DataFunc3(controller.List, Query[dto.DriverListQueryFilter](QueryParamError), Query[common.PageQueryFilter](QueryParamError), Query[common.SortQueryFilter](QueryParamError)))
	engine.Post(strings.TrimPrefix("/v1/storages/drivers", groupPrefix), Func1(controller.Create, Body[dto.DriverForm](BodyParamError)))
	engine.Put(strings.TrimPrefix("/v1/storages/drivers/:id<int>", groupPrefix), Func2(controller.Update, Integer[uint64]("id", PathParamError), Body[dto.DriverForm](BodyParamError)))
	engine.Delete(strings.TrimPrefix("/v1/storages/drivers/:id<int>", groupPrefix), Func1(controller.Delete, Integer[uint64]("id", PathParamError)))
}
